// Frontend แสดง Runtime State เท่านั้น; การ READ/MODIFY/WRITE และ Lock เกิดใน Java Backend จริง
let timer=null, compareTimer=null, lastEvents=-1, runNo=0, inspected=null, replayTimer=null, replayItems=[], replayIndex=0; const results={race:null,sync:null},history=[], replayData={race:null,sync:null},completedStates={race:null,sync:null}; const $=x=>document.getElementById(x);
const esc=x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
async function post(url,data={}){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),b=await r.json();if(!r.ok)throw Error(b.error||'Request failed');return b}
function formula(){let t=+$('threads').value||0,i=+$('iterations').value||0;$('formula').textContent=`${t} × ${i} = ${t*i}`;$('sameFormula').textContent=`${t} Threads × ${i} Iterations • Expected ${t*i}`;if(!timer&&!compareTimer){$('expected').textContent=t*i;$('progressText').textContent=`0 / ${t*i}`}}
const phaseLabel=p=>({READ:'กำลังอ่าน (READ)',MODIFY:'กำลังคำนวณ (MODIFY)',WRITE:'กำลังเขียน (WRITE)','WAIT LOCK':'กำลังรอ Lock (WAITING FOR LOCK)',DONE:'เสร็จสิ้น (COMPLETED)',COMPLETED:'เสร็จสิ้น (COMPLETED)',READY:'พร้อมทำงาน (READY)',BARRIER:'รอเริ่มพร้อมกัน (START BARRIER)','AFTER WRITE':'ปล่อย Lock แล้ว (RELEASED)',RUNNING:'กำลังทำงาน (RUNNING)',LOCKED:'ถือ Lock อยู่ (LOCK OWNER)'})[p]||p;
function explainThread(t,s){if(t.phase==='READ')return `อ่าน Shared Counter = ${t.readValue} มาเก็บเป็น Local Value`;if(t.phase==='MODIFY')return `คำนวณ ${t.readValue} + 1 → Local Value = ${t.localValue}`;if(t.phase==='WRITE')return `เขียน Local ${t.writeValue} กลับ Shared Counter (ก่อนเขียน = ${t.sharedBefore})`;if(t.phase==='WAIT LOCK'){let owner=s.holder!=='-'?s.holder:t.waitingFor;return `รอ ${owner||'Thread ที่ถือ Lock'} ปล่อย ReentrantLock ก่อนเข้า Critical Section`;}if(t.phase==='DONE')return 'ทำงานครบทุก Iteration แล้ว';return t.operation||t.phase}
function threadCard(t,s,compact=false,lane='single'){let owner=s.holder!=='-'?s.holder:t.waitingFor,wait=t.phase==='WAIT LOCK';return `<article role="button" tabindex="0" aria-label="เปิดประวัติ ${esc(t.name)}" onclick="openInspector('${lane}','${esc(t.name)}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();openInspector('${lane}','${esc(t.name)}')}" class="thread p-${t.phase.toLowerCase().replaceAll(' ','-')} ${compact?'compact':''}"><div class="thread-head"><div><b>${esc(t.name)}</b><small>รอบ (Iteration) ${t.iteration} / ${s.iterations}</small></div><span>${esc(phaseLabel(t.phase))}</span></div><div class="phase-name">${esc(phaseLabel(t.phase))}</div><p>${esc(explainThread(t,s))}</p><div class="dataflow"><div><small>READ / ค่าที่อ่าน</small><b>${t.readValue}</b></div><i>→</i><div><small>LOCAL / ค่าที่คำนวณ</small><b>${t.localValue}</b></div><i>→</i><div><small>WRITE / ค่าที่จะเขียน</small><b>${t.writeValue}</b></div></div>${wait?`<div class="waiting-for">⏳ <b>กำลังรอ ${esc(owner)} / Waiting for ${esc(owner)}</b><br><span>${esc(owner)} เป็น Lock Owner • เมื่อปล่อย Lock จะได้ ACQUIRED แล้ว RUNNING</span></div>`:''}<div class="thread-summary"><span>Writes <b>${t.writes||0}</b></span><span>สำเร็จ <b>${t.successful||0}</b></span><span>Lost <b>${t.lost||0}</b></span><span>รอ Lock <b>${t.lockWaits||0}</b></span><span>จบรอบ <b>${t.completedIterations||0}</b></span></div><small class="inspect-hint">กดเพื่อดู Thread Inspector / Click to inspect →</small><div class="progress"><i style="width:${Math.min(100,t.iteration/s.iterations*100)}%"></i></div></article>`}
function eventLine(e){let c=e.includes('READ ')?'r':e.includes('MODIFY')?'m':e.includes('WRITE ')?'w':e.includes('WAIT')?'wait':e.includes('LOCK')?'l':'';let th=e.includes('READ ')?'กำลังอ่าน Shared Counter (READ)':e.includes('MODIFY')?'กำลังคำนวณ Local Value (MODIFY)':e.includes('WRITE ')?'กำลังเขียนค่ากลับ Shared Counter (WRITE)':e.includes('Waiting for ReentrantLock')?'กำลังรอผู้ถือ Lock ปล่อย Lock (WAITING FOR LOCK)':e.includes('ACQUIRED LOCK')?'ได้ Lock และเข้า Critical Section (ACQUIRED LOCK)':e.includes('RELEASED LOCK')?'ปล่อย Lock แล้ว (RELEASE LOCK)':e.includes('Finished.')?'การทดลองเสร็จสิ้น (COMPLETED)':e.includes('Simulation started')?'เริ่มการทดลอง (CREATED)':'';return `<div class="event ${c}">${esc(e)}${th?`<small class="event-thai">${th}</small>`:''}</div>`}
function renderLost(s){const a=s.lostEvents||[],finalGap=Math.max(0,s.expected-s.counter);$('lostTotal').textContent=s.lostUpdates??a.length;$('lostExplain').innerHTML=a.length?`ตรวจพบจากการเขียนจริง <b>${a.length}</b> เหตุการณ์${s.running?' ระหว่างการทดลอง':''}${!s.running?` • Expected ${s.expected} − Actual ${s.counter} = <b>${finalGap}</b>`:''}`:s.running?'ขณะนี้ยังไม่พบ Lost Update • ผลอาจเปลี่ยนได้ตามจังหวะ Thread':'รอบนี้ไม่พบ Lost Update จาก event จริง'+(s.mode==='race'?' แม้ไม่มี Lock ก็ไม่ได้แปลว่าจะเกิดข้อมูลหายทุกครั้ง':' เพราะ Lock ป้องกันการแทรกระหว่างอ่านและเขียน');$('lostEvents').innerHTML=a.length?a.slice().reverse().map((x,i)=>`<div class="lost-event"><b>💥 ข้อมูลอัปเดตหาย (LOST UPDATE) #${a.length-i}</b><p>${esc(x)}</p><small>หลักฐานนี้บันทึกตอน Worker เขียนค่า ไม่ได้สร้างจากตัวอย่างจำลอง</small></div>`).join(''):'<div class="empty-state">'+(s.running?'ยังไม่พบเหตุการณ์ในรอบนี้':'รอบนี้ไม่มี Lost Update')+'</div>'}
function renderSingle(s){window.singleState=s;$('counter').textContent=s.counter;$('actual').textContent=s.counter;$('expected').textContent=s.expected;$('completed').textContent=s.completed;$('lost').textContent=s.lostUpdates??0;$('holder').textContent=s.holder==='-'?'ไม่มี / None':s.holder;$('progressText').textContent=`${s.completed} / ${s.total}`;$('live').textContent=s.paused?'PAUSED / หยุด':s.running?'RUNNING / กำลังทำงาน':'IDLE / ว่าง';$('live').className='pill '+(s.paused?'paused':s.running?'on':'');$('lockGate').textContent=s.mode==='sync'?(s.holder==='-'?'🔓 LOCK AVAILABLE / LOCK ว่าง':`🔒 ${s.holder} HOLDS LOCK / ถือ LOCK`):'⚠ NO LOCK / ไม่มีการป้องกัน';$('lockGate').className='gate '+(s.mode==='sync'?'safe':'unsafe');$('threadsView').innerHTML=s.threads.map(t=>threadCard(t,s,false,'single')).join('');$('insight').textContent=s.insight;$('highlights').innerHTML=(s.highlights||[]).slice().reverse().map(x=>`<div>${esc(x)}</div>`).join('');renderLost(s);if(s.events.length!==lastEvents){$('events').innerHTML=s.events.map(eventLine).join('');$('events').scrollTop=$('events').scrollHeight;lastEvents=s.events.length}if(!s.running&&timer){clearInterval(timer);timer=null;setDisabled(false);finishResult(s)}}
function laneInsight(s){if(s.mode==='sync'){if(s.holder!=='-'){let waiting=s.threads.filter(t=>t.phase==='WAIT LOCK').map(t=>t.name);return `🔒 ${s.holder} อยู่ใน Critical Section${waiting.length?` • ${waiting.join(', ')} กำลังรอ ${s.holder} ปล่อย Lock`:''}`;}return '🔓 ReentrantLock ว่าง • Thread ถัดไปสามารถเข้า Critical Section ได้';}let same={};s.threads.filter(t=>['READ','MODIFY','WRITE'].includes(t.phase)).forEach(t=>(same[t.readValue]??=[]).push(t.name));let hit=Object.entries(same).find(([,a])=>a.length>1);return hit?`⚠ ${hit[1].join(', ')} กำลังทำงานจากค่าที่อ่าน = ${hit[0]} เหมือนกัน • มีความเสี่ยง Lost Update`:'หลาย Thread ทำงานได้พร้อมกันโดยไม่มี Lock ป้องกัน Shared Counter';}
function renderCompareState(d){window.compareState=d;let a=d.race,b=d.sync;$('raceCounter').textContent=a.counter;$('syncCounter').textContent=b.counter;$('raceThreads').innerHTML=a.threads.map(t=>threadCard(t,a,true,'race')).join('');$('syncThreads').innerHTML=b.threads.map(t=>threadCard(t,b,true,'sync')).join('');$('raceNow').textContent=laneInsight(a);$('syncNow').textContent=laneInsight(b);$('syncOwner').innerHTML=b.holder==='-'?'🔓 Lock available / Lock ว่าง':`🔒 Lock owner / ผู้ถือ Lock: <b>${esc(b.holder)}</b>`;$('compareLive').textContent=(a.running||b.running)?((a.paused||b.paused)?'PAUSED / หยุด':'RUNNING / กำลังทำงาน'):'COMPLETED / เสร็จ';$('actual').textContent=`${a.counter} | ${b.counter}`;$('expected').textContent=a.expected;$('completed').textContent=`${a.completed} | ${b.completed}`;$('lost').textContent=`${a.lostUpdates??0} | ${b.lostUpdates??0}`;$('progressText').textContent='No Sync | ReentrantLock';$('insight').textContent=`ฝั่งซ้าย: ${laneInsight(a)}  •  ฝั่งขวา: ${laneInsight(b)}`;$('highlights').innerHTML=[...(a.highlights||[]).slice(-3),...(b.highlights||[]).slice(-2)].reverse().map(x=>`<div>${esc(x)}</div>`).join('');renderLost(a);$('events').innerHTML=`<div class="log-columns"><div><b>WITHOUT SYNC</b>${a.events.map(eventLine).join('')}</div><div><b>REENTRANTLOCK</b>${b.events.map(eventLine).join('')}</div></div>`;if(!a.running&&!b.running&&compareTimer){clearInterval(compareTimer);compareTimer=null;setDisabled(false);finishResult(a);finishResult(b);renderComparison()}}
function setDisabled(v){['threads','iterations','delay','race','sync','compare'].forEach(x=>$(x).disabled=v)}
async function refresh(){try{renderSingle(await fetch('/api/state').then(r=>r.json()))}catch(e){$('live').textContent='OFFLINE'}}
async function refreshCompare(){try{renderCompareState(await fetch('/api/compare/state').then(r=>r.json()))}catch(e){$('compareLive').textContent='OFFLINE'}}
async function start(mode){if(timer||compareTimer)return;hideError();$('compareLab').classList.add('hidden');$('singleLab').classList.remove('hidden');try{await post('/api/start',{threads:+$('threads').value,iterations:+$('iterations').value,delay:+$('delay').value,mode});setDisabled(true);lastEvents=-1;timer=setInterval(refresh,80);refresh()}catch(e){showError(e.message)}}
async function startCompare(){if(timer||compareTimer)return;hideError();results.race=results.sync=null;$('singleLab').classList.add('hidden');$('compareLab').classList.remove('hidden');try{await post('/api/compare/start',{threads:+$('threads').value,iterations:+$('iterations').value,delay:+$('delay').value});setDisabled(true);compareTimer=setInterval(refreshCompare,80);refreshCompare()}catch(e){showError(e.message)}}
function finishResult(s){if(!s.completed)return;let r={mode:s.mode,threads:s.threadsConfigured,iterations:s.iterations,expected:s.expected,actual:s.counter,lost:Math.max(0,s.expected-s.counter),observedLost:s.lostUpdates??0,race:s.race};results[s.mode]=r;completedStates[s.mode]=s;replayData[s.mode]=captureReplay(s);history.push({...r,no:++runNo});renderHistory();renderComparison()}
function captureReplay(s){return s.threads.flatMap(t=>(t.history||[]).map(e=>({...e,thread:t.name,lane:s.mode==='sync'?'withLock':'noLock'}))).sort((a,b)=>a.ms-b.ms)}
function renderHistory(){$('history').innerHTML=history.slice().reverse().map(r=>`<tr><td>#${r.no}</td><td><b>${r.mode==='sync'?'ReentrantLock':'ไม่มี Lock'}</b></td><td>${r.threads}</td><td>${r.iterations}</td><td>${r.expected}</td><td>${r.actual}</td><td>${r.lost}</td><td>${r.race?'พบค่าคลาดเคลื่อน':'ค่าตรงตามคาด'}</td></tr>`).join('')}
function renderComparison(){let a=results.race,b=results.sync;let cell=(v)=>v==null?'—':v;$('compareTable').innerHTML=`<tr><td><b>จำนวน Thread</b></td><td>${cell(a?.threads)}</td><td>${cell(b?.threads)}</td><td>Worker ที่ทำงานร่วมกัน</td></tr><tr><td><b>จำนวนรอบต่อ Thread</b></td><td>${cell(a?.iterations)}</td><td>${cell(b?.iterations)}</td><td>จำนวนครั้งที่แต่ละตัวเพิ่มค่า</td></tr><tr><td><b>ควรได้ (EXPECTED)</b></td><td>${cell(a?.expected)}</td><td>${cell(b?.expected)}</td><td>Thread × รอบ</td></tr><tr><td><b>ได้จริง (ACTUAL)</b></td><td class="bad">${cell(a?.actual)}</td><td class="good">${cell(b?.actual)}</td><td>Shared Counter หลังจบ</td></tr><tr><td><b>ค่าที่หาย (LOST UPDATE)</b></td><td class="bad">${cell(a?.lost)}</td><td class="good">${cell(b?.lost)}</td><td>Expected − Actual</td></tr><tr><td><b>วิธีป้องกัน</b></td><td>ไม่มี Lock</td><td>🔒 ReentrantLock แบบเข้าคิว</td><td>ล็อก READ → MODIFY → WRITE</td></tr>`;if(a&&b){const raceNote=a.lost?`พบ Lost Update ${a.lost} ครั้ง`:"รอบนี้ไม่มี Lost Update แม้ไม่ใช้ Lock เพราะผลขึ้นกับจังหวะการทำงาน";$('comparisonExplain').innerHTML=`<b>สรุปผลรอบนี้:</b> ทั้งสองฝั่งใช้ ${a.threads} Thread × ${a.iterations} รอบ = ควรได้ ${a.expected}. ไม่มี Lock ได้จริง ${a.actual} (${raceNote}); ReentrantLock ได้จริง ${b.actual} และหาย ${b.lost}. Lock ทำให้แต่ละ Thread ทำชุดอ่าน → คำนวณ → เขียนต่อเนื่องทีละตัว`}}
function showError(x){$('error').textContent=x;$('error').classList.remove('hidden')}function hideError(){$('error').classList.add('hidden')}
$('race').onclick=()=>start('race');$('sync').onclick=()=>start('sync');$('compare').onclick=startCompare;$('pause').onclick=()=>post('/api/control',{action:'pause'}).then(refresh);$('resume').onclick=()=>post('/api/control',{action:'resume'}).then(refresh);$('step').onclick=()=>post('/api/control',{action:'step'}).then(()=>setTimeout(refresh,40));$('comparePause').onclick=()=>post('/api/compare/control',{action:'pause'}).then(refreshCompare);$('compareResume').onclick=()=>post('/api/compare/control',{action:'resume'}).then(refreshCompare);$('compareStep').onclick=()=>post('/api/compare/control',{action:'step'}).then(()=>setTimeout(refreshCompare,40));$('reset').onclick=async()=>{if(timer||compareTimer)return;await post('/api/reset');$('compareLab').classList.add('hidden');$('singleLab').classList.remove('hidden');lastEvents=-1;refresh();formula()};$('toggleLog').onclick=()=>$('events').classList.toggle('hidden');['threads','iterations'].forEach(x=>$(x).addEventListener('input',formula));formula();refresh();

// Thread Inspector reads the event history serialized by the Java backend.
window.openInspector=function(lane,name){
  const state=lane==='single'?window.singleState:window.compareState?.[lane];if(!state)return;
  const t=state.threads.find(x=>x.name===name);if(!t)return;
  inspected={lane,name};const mode=lane==='race'?'ไม่มี Lock (WITHOUT SYNCHRONIZATION)':lane==='sync'?'ใช้ ReentrantLock (WITH SYNCHRONIZATION)':state.mode==='sync'?'ใช้ ReentrantLock':'ไม่มี Lock';
  $('inspectorTitle').textContent=`${name} • ${mode}`;$('inspectorSub').textContent='ประวัติและค่าที่อ่าน/เขียนจาก Java Worker ตัวนี้จริง';
  $('inspectorSummary').innerHTML=`<span>จำนวนครั้งที่เขียน (Writes) <b>${t.writes||0}</b></span><span>อัปเดตสำเร็จ (Successful) <b>${t.successful||0}</b></span><span>อัปเดตหาย (Lost) <b>${t.lost||0}</b></span><span>รอ Lock (Waits) <b>${t.lockWaits||0}</b></span><span>จบรอบ (Completed) <b>${t.completedIterations||0}</b></span>`;
  const sel=$('iterationFilter');sel.innerHTML='<option value="ALL">ทุก Iteration</option>'+Array.from({length:state.iterations},(_,i)=>`<option value="${i+1}">รอบที่ ${i+1}</option>`).join('');$('eventFilter').value='ALL';sel.value='ALL';renderInspector();$('inspectorModal').classList.remove('hidden')
};
function renderInspector(){
  if(!inspected)return;
  const state=inspected.lane==='single'?window.singleState:window.compareState?.[inspected.lane],t=state?.threads.find(x=>x.name===inspected.name);
  if(!t)return;
  let events=t.history||[],kind=$('eventFilter').value,iter=$('iterationFilter').value;
  if(kind!=='ALL')events=events.filter(e=>kind==='LOCK'?e.type.includes('LOCK'):kind==='WAIT'?e.type.includes('WAIT'):kind==='LOST UPDATE'?e.type==='LOST UPDATE':e.type===kind);
  if(iter!=='ALL')events=events.filter(e=>e.iteration===+iter);
  const labels={CREATED:'สร้าง Thread (CREATED)',ITERATION:'เริ่มรอบ (ITERATION)',RUNNING:'กำลังทำงาน (RUNNING)',READ:'กำลังอ่าน (READ)',MODIFY:'กำลังคำนวณ (MODIFY)',WRITE:'กำลังเขียน (WRITE)','LOST UPDATE':'ข้อมูลอัปเดตหาย (LOST UPDATE)','REQUEST LOCK':'ขอ Lock (REQUEST LOCK)','WAITING FOR LOCK':'กำลังรอ Lock (WAITING FOR LOCK)','ACQUIRED LOCK':'ได้ Lock (ACQUIRED LOCK)','RELEASE LOCK':'ปล่อย Lock (RELEASE LOCK)',COMPLETED:'เสร็จสิ้น (COMPLETED)'};
  const cls=e=>e.type.includes('WAIT')?'wait':e.type.includes('LOCK')?'lock':e.type==='READ'?'read':e.type==='MODIFY'?'modify':e.type==='WRITE'?'write':e.type.includes('LOST')?'lost':'';
  $('inspectorTimeline').innerHTML=events.length?events.map(e=>`<article class="timeline-item ${cls(e)}"><div class="timeline-dot"></div><div class="timeline-content"><div class="timeline-heading"><b>${labels[e.type]||esc(e.type)}</b><small>${(e.ms/1000).toFixed(3)} วินาที • ${e.iteration?`รอบที่ ${e.iteration}`:'ก่อนเริ่ม'}</small></div><p>${esc(e.detail)}</p><div class="timeline-values"><span>Shared ก่อน→หลัง: ${e.sharedBefore} → ${e.sharedAfter}</span><span>ค่าที่อ่าน (READ): ${e.readValue}</span><span>ค่าใน Thread (LOCAL): ${e.localValue}</span></div></div></article>`).join(''):'<div class="empty-state">ไม่พบเหตุการณ์ตามตัวกรองนี้</div>'
}
$('closeInspector').onclick=()=>$('inspectorModal').classList.add('hidden');$('inspectorModal').addEventListener('click',e=>{if(e.target===$('inspectorModal'))$('inspectorModal').classList.add('hidden')});$('eventFilter').onchange=renderInspector;$('iterationFilter').onchange=renderInspector;document.addEventListener('keydown',e=>{if(e.key==='Escape')$('inspectorModal').classList.add('hidden')});

// Export and replay operate on completed snapshots returned by the Java backend.
function downloadFile(name,type,body){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([body],{type}));a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function exportJson(){const modes=['race','sync'].filter(m=>completedStates[m]);if(!modes.length){showError('ยังไม่มีผลทดลองให้ส่งออก ลองรันการทดลองให้จบก่อนนะ');return}downloadFile('threadsync-results.json','application/json;charset=utf-8',JSON.stringify({exportedAt:new Date().toISOString(),runs:modes.map(m=>({summary:results[m],state:completedStates[m]}))},null,2))}
function csvCell(v){return '"'+String(v??'').replaceAll('"','""')+'"'}
function exportCsv(){const modes=['race','sync'].filter(m=>completedStates[m]);if(!modes.length){showError('ยังไม่มีผลทดลองให้ส่งออก ลองรันการทดลองให้จบก่อนนะ');return}const rows=[['Mode','Thread','Event','Iteration','Elapsed ms','Read Value','Local Value','Shared Before','Shared After','Detail']];for(const m of modes)for(const t of completedStates[m].threads)for(const e of t.history||[])rows.push([m==='race'?'ไม่มี Lock':'ReentrantLock',t.name,e.type,e.iteration,e.ms,e.readValue,e.localValue,e.sharedBefore,e.sharedAfter,e.detail]);downloadFile('threadsync-events.csv','text/csv;charset=utf-8','\ufeff'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n'))}
const replayLabels={'CREATED':'สร้าง Thread (CREATED)','ITERATION':'เริ่มรอบ (ITERATION)','RUNNING':'กำลังทำงาน (RUNNING)','READ':'กำลังอ่าน (READ)','MODIFY':'กำลังคำนวณ (MODIFY)','WRITE':'กำลังเขียน (WRITE)','LOST UPDATE':'ข้อมูลอัปเดตหาย (LOST UPDATE)','REQUEST LOCK':'ขอ Lock (REQUEST LOCK)','WAITING FOR LOCK':'กำลังรอ Lock (WAITING FOR LOCK)','ACQUIRED LOCK':'ได้ Lock (ACQUIRED LOCK)','RELEASE LOCK':'ปล่อย Lock (RELEASE LOCK)','COMPLETED':'เสร็จสิ้น (COMPLETED)'};
function replayEventHtml(e){const label=replayLabels[e.type]||e.type,kind=e.type.includes('WAIT')?'wait':e.type.includes('LOCK')?'lock':e.type==='READ'?'read':e.type==='MODIFY'?'modify':e.type==='WRITE'?'write':e.type.includes('LOST')?'lost':'';return `<article class="timeline-item ${kind}"><div class="timeline-dot"></div><div class="timeline-content"><div class="timeline-heading"><b>${esc(label)} • ${esc(e.thread)}</b><small>${e.lane==='withLock'?'มี Lock':'ไม่มี Lock'} · รอบ ${e.iteration||'—'} · ${(e.ms/1000).toFixed(2)}s</small></div><p>${esc(e.detail)}</p><div class="timeline-values"><span>Shared ${e.sharedBefore} → ${e.sharedAfter}</span><span>อ่าน ${e.readValue}</span><span>Local ${e.localValue}</span></div></div></article>`}
function renderReplay(){if(!replayItems.length)return;replayIndex=Math.max(0,Math.min(replayIndex,replayItems.length-1));$('replayRange').value=replayIndex;$('replayProgress').textContent=`เหตุการณ์ ${replayIndex+1} / ${replayItems.length}`;const e=replayItems[replayIndex];$('replayCurrent').innerHTML=`<div class="replay-focus"><small>กำลังดูเหตุการณ์นี้</small>${replayEventHtml(e)}</div>`;$('replayTimeline').innerHTML=replayItems.slice(Math.max(0,replayIndex-5),replayIndex+1).reverse().map(replayEventHtml).join('')}
function replayStep(n){replayIndex=Math.max(0,Math.min(replayItems.length-1,replayIndex+n));renderReplay();if(replayIndex===replayItems.length-1&&replayTimer){clearInterval(replayTimer);replayTimer=null;$('replayPlay').textContent='▶ เล่นอีกครั้ง'}}
function toggleReplay(){if(replayTimer){clearInterval(replayTimer);replayTimer=null;$('replayPlay').textContent='▶ เล่น';return}if(replayIndex>=replayItems.length-1)replayIndex=-1;$('replayPlay').textContent='Ⅱ หยุด';replayTimer=setInterval(()=>replayStep(1),+$('replaySpeed').value)}
function openReplay(){if(replayTimer){clearInterval(replayTimer);replayTimer=null}const modes=['race','sync'].filter(m=>replayData[m]);if(!modes.length){showError('ยังไม่มีประวัติให้เล่นซ้ำ ต้องรันการทดลองให้จบก่อน');return}replayItems=modes.flatMap(m=>replayData[m]||[]).sort((a,b)=>a.ms-b.ms);replayIndex=0;$('replayRange').max=Math.max(0,replayItems.length-1);$('replayRange').value='0';$('replayModal').classList.remove('hidden');renderReplay()}
$('demo').onclick=()=>{$('threads').value=3;$('iterations').value=5;$('delay').value=600;formula();$('insight').textContent='ตั้งค่าสาธิตแล้ว: 3 Thread × 5 รอบ • กดเปรียบเทียบเพื่อดูความแตกต่างสองวิธี'};
$('export').onclick=exportJson;$('exportCsv').onclick=exportCsv;$('replay').onclick=openReplay;$('closeReplay').onclick=()=>{$('replayModal').classList.add('hidden');if(replayTimer){clearInterval(replayTimer);replayTimer=null}};$('replayModal').addEventListener('click',e=>{if(e.target===$('replayModal'))$('closeReplay').click()});$('replayPlay').onclick=toggleReplay;$('replayPrev').onclick=()=>replayStep(-1);$('replayNext').onclick=()=>replayStep(1);$('replayRange').oninput=()=>{replayIndex=+$('replayRange').value;renderReplay()};$('replaySpeed').onchange=()=>{if(replayTimer){clearInterval(replayTimer);replayTimer=null;toggleReplay()}};document.addEventListener('keydown',e=>{if(e.key==='Escape')$('replayModal').classList.add('hidden')});
setInterval(()=>{if(!inspected||$('inspectorModal').classList.contains('hidden'))return;const st=inspected.lane==='single'?window.singleState:window.compareState?.[inspected.lane],th=st?.threads.find(x=>x.name===inspected.name);if(!th)return;$('inspectorSummary').innerHTML=`<span>จำนวนครั้งที่เขียน (Writes) <b>${th.writes||0}</b></span><span>อัปเดตสำเร็จ (Successful) <b>${th.successful||0}</b></span><span>อัปเดตหาย (Lost) <b>${th.lost||0}</b></span><span>รอ Lock (Waits) <b>${th.lockWaits||0}</b></span><span>จบรอบ (Completed) <b>${th.completedIterations||0}</b></span>`;renderInspector()},450);
